---
# Install Azure CLI on Linux
- name: Install Azure CLI on Linux
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  args:
    warn: no
  when: ansible_system == "Linux"

# Install Azure CLI on MacOS
- name: Install Azure CLI on MacOS
  homebrew:
    name: azure-cli
    state: present
  when: ansible_os_family == "Darwin"

  # Is azure cli installed?
- command: az --version
  register: result
  failed_when: false
  changed_when: false

- debug:
    var: result.stdout