---
- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 0
  vars:
    packages:
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg

- name: Add Microsoft key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: install microsoft repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
    filename: azure-cli
  when: ansible_distribution == 'Ubuntu'

- name: install microsoft repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main"
    state: present
    filename: azure-cli
  when: ansible_distribution == 'Linux Mint'
  
- name: install azure-cli
  apt:
    name: azure-cli
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes

...
